</div>


<div class-"row">
<footer class="col-xs-12 align-bottom">
    <p>Auction Website made with bootstrap and php 12/2020©</p>
</footer>
</div>

<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
<script src="js/bootstrap.min.js"></script>
</body>
</html>